In [1]:
import numpy as np

In [2]:
lista = [1,2,3]
array = np.array(lista)

In [3]:
array

array([1, 2, 3])

In [5]:
array[1]

2

In [9]:
np.arange(5,30,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [11]:
np.ones(shape=(10,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
np.zeros(shape=(10,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
np.ones(shape=(10,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
aleatorios = np.random.randint(0,100,50)

In [15]:
aleatorios

array([53, 34, 54, 70, 92, 98,  0, 28, 14, 96, 73,  1, 53, 41, 27, 32, 42,
       62, 10, 76, 36, 11, 58, 13, 68, 76, 16, 23, 30, 90, 64, 35, 17, 78,
       51, 59, 14, 65, 58, 71, 63, 17, 84, 61, 34, 74, 32, 57, 34, 79])

In [16]:
aleatorios.argmax()

5

In [17]:
aleatorios.max()

98

In [19]:
aleatorios.min()

0

In [20]:
aleatorios.argmin()

6

In [21]:
aleatorios.shape

(50,)

In [22]:
aleatorios = aleatorios.reshape(10,5)

In [23]:
aleatorios

array([[53, 34, 54, 70, 92],
       [98,  0, 28, 14, 96],
       [73,  1, 53, 41, 27],
       [32, 42, 62, 10, 76],
       [36, 11, 58, 13, 68],
       [76, 16, 23, 30, 90],
       [64, 35, 17, 78, 51],
       [59, 14, 65, 58, 71],
       [63, 17, 84, 61, 34],
       [74, 32, 57, 34, 79]])

In [24]:
aleatorios[0,0]

53

In [25]:
aleatorios[1,1]

0

In [30]:
aleatorio = np.random.randint(0,100,50)